name: Multi-Platform Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build on Linux
        if: runner.os == 'Linux'
        run: make
      
      - name: Build on Windows
        if: runner.os == 'Windows'
        run: g++ -std=c++17 -o hoj-cli main.cpp -lws2_32
      
      - name: Upload Linux to Release
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/hoj-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Windows to Release
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: hoj-cli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}